version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: carwash
      POSTGRES_PASSWORD: carwash
      POSTGRES_DB: carwash
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://carwash:carwash@db:5432/carwash
      JWT_SECRET: supersecret
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  db-data:
